import sbt.Keys._
import Version._
// import com.typesafe.sbt.osgi.SbtOsgi._

// scm/url/developers are generated by sbt + sbt-git from the git remote, so we don't
// repeat them here. Including them caused Artifactory to reject the POM with
// "Duplicated tag: 'scm'".
lazy val extra = <licenses>
    <license>
      <name>Apache 2</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>;

// git.useGitDescribe := true

val VersionRegex = "v([0-9]+.[0-9]+.[0-9]+)-?(.*)?".r


lazy val commonSettings = Seq(
  organization := "org.scalanlp",
  version := "0.4.5-fs2-SNAPSHOT",
  /*
  git.baseVersion := "0.4",
  // append -SNAPSHOT unless we're on a branch
  git.gitUncommittedChanges := false,//git.gitCurrentTags.value.isEmpty,
  isSnapshot := false,
  git.gitTagToVersionNumber := { v: String =>
    v match {
      case VersionRegex(v,"") => Some(v)
      case VersionRegex(v,"SNAPSHOT") => Some(s"$v-SNAPSHOT")
      case VersionRegex(v,s) => Some(s"$v-$s-SNAPSHOT")
      case _ => None
    }
  },
  */
  crossScalaVersions := Seq("2.12.10", "2.11.8"),
  libraryDependencies ++= Seq(
    Library.breeze,
    Library.breezeConfig,
    Library.mapdb,
    Library.slf4jSimple,
    Library.commonsLang3,
    Library.jflex,
    Library.scalatest % "test",
    Library.scalacheck % "test",
    Library.junit % "test"
  ),
  scalacOptions ++= Seq("-deprecation", "-language:_", "-optimize", "-release:11"),
  javacOptions ++= Seq("--release", "11"),
  javaOptions += "-Xmx6g",
  //javaOptions += "-Xrunhprof:cpu=samples,depth=12",
  fork := true,
  publishMavenStyle := true,
  pomExtra := extra,
  publishTo := {
    val artifactory = "https://foursquaredev.jfrog.io/foursquaredev/"
    if (isSnapshot.value)
      Some("fsfactual-snapshots-local" at artifactory + "fsfactual-snapshots-local")
    else
      Some("fsfactual-releases-local" at artifactory + "fsfactual-releases-local")
  },
  credentials += Credentials(Path.userHome / ".sbt" / ".credentials"),
  publishArtifact in Test := false,
  pomIncludeRepository := { _ => false },
  assemblyOption in assembly ~= {
    _.copy(cacheOutput = false)
  },
  resolvers ++= Seq(
    "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
  ),
  libraryDependencies ++= Seq("org.scala-lang.modules" %% "scala-xml" % "1.0.6")
  ) ++ sbtjflex.SbtJFlexPlugin.jflexSettings
  // ++ net.virtualvoid.sbt.graph.Plugin.graphSettings
  
  // TODO rewrite in sbt 1.x syntax
  /* ++
  IndexedSeq (
      mergeStrategy in assembly <<= (mergeStrategy in assembly) { (old) =>
        {
          case PathList("org", "w3c", "dom", _) => MergeStrategy.first
          case PathList("javax", "xml", "stream", _ *) => MergeStrategy.first
          case PathList("scala", "xml", _ *) => MergeStrategy.first
          case PathList("org", "cyberneko", "html", _ *) => MergeStrategy.first
          case x => old(x)
         }
      }
  )*/

lazy val epicCore = project
  .in(file("modules/core"))
  //.enablePlugins(GitVersioning)
  .settings(commonSettings)
  .settings(
    name := "epic"
    //,
    //OsgiKeys.privatePackage := Seq(),
    //OsgiKeys.importPackage := Seq("org.apache.tika.*; resolution:=optional", "*"),
    //OsgiKeys.exportPackage := Seq("epic.*")
  )

lazy val epicHtml = project
  .in(file("modules/html"))
  .dependsOn(epicCore)
  .settings(
    commonSettings,
    name := "epic-html",
    libraryDependencies ++= Seq(
       Library.tikaParsers,
       Library.boilerpipe,
       Library.nekohtml,
    )
  )
